import {
  Dashboard as DashboardIcon,
  People as PeopleIcon,
  Settings as SettingsIcon,
  ShoppingCart as ShoppingCartIcon,
  Inventory as InventoryIcon,
  Assessment as ReportsIcon,
  Security as SecurityIcon,
  Person as PersonIcon,
  Group as GroupIcon,
  AdminPanelSettings as AdminIcon,
  BarChart as ChartIcon,
  TrendingUp as TrendingIcon,
  TableChart as TableIcon,
  PieChart as PieIcon,
  Timeline as TimelineIcon,
  Store as StoreIcon,
  Category as CategoryIcon,
  LocalShipping as ShippingIcon,
  Payment as PaymentIcon,
  Receipt as OrderIcon,
  Star as ReviewIcon,
  Notifications as NotificationIcon,
  Lock as LockIcon,
  VpnKey as KeyIcon,
  Shield as ShieldIcon,
  Description,
  Analytics,
  People,
  TaskAlt,
  LockPerson,
  HowToReg,
} from "@mui/icons-material";

export const menuData = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: DashboardIcon,
    path: "/dashboard",
  },
  {
    id: "role",
    title: "Role Management",
    icon: Analytics,
    path: "/role",
  },
  {
    id: "user",
    title: "User Management",
    icon: People,
    path: "/user",
  },
  {
    id: "approval",
    title: "User Approval",
    path: "/approval",
    icon: HowToReg,
  },
  {
    id: "permission",
    title: "Permission Management",
    path: "/permission",
    icon: LockPerson,
  },
  {
    id: "permission_approval",
    title: "Permission Approval",
    path: "/permission_approval",
    icon: TaskAlt,
  },
  //   {
  //     id: "users",
  //     title: "User Management",
  //     icon: PeopleIcon,
  //     children: [
  //       {
  //         id: "all-users",
  //         title: "All Users",
  //         icon: PersonIcon,
  //         path: "/users/all",
  //       },
  //       {
  //         id: "user-groups",
  //         title: "User Groups",
  //         icon: GroupIcon,
  //         children: [
  //           {
  //             id: "admin-group",
  //             title: "Administrators",
  //             icon: AdminIcon,
  //             path: "/users/groups/admin",
  //           },
  //           {
  //             id: "manager-group",
  //             title: "Managers",
  //             icon: PersonIcon,
  //             path: "/users/groups/managers",
  //           },
  //           {
  //             id: "customer-group",
  //             title: "Customers",
  //             icon: PersonIcon,
  //             path: "/users/groups/customers",
  //           },
  //         ],
  //       },
  //       {
  //         id: "user-roles",
  //         title: "Roles & Permissions",
  //         icon: SecurityIcon,
  //         path: "/users/roles",
  //       },
  //     ],
  //   },
  //   {
  //     id: "analytics",
  //     title: "Analytics",
  //     icon: AnalyticsIcon,
  //     children: [
  //       {
  //         id: "reports",
  //         title: "Reports",
  //         icon: ReportsIcon,
  //         children: [
  //           {
  //             id: "sales-reports",
  //             title: "Sales Reports",
  //             icon: ChartIcon,
  //             path: "/analytics/reports/sales",
  //           },
  //           {
  //             id: "user-reports",
  //             title: "User Reports",
  //             icon: TrendingIcon,
  //             path: "/analytics/reports/users",
  //           },
  //           {
  //             id: "financial-reports",
  //             title: "Financial Reports",
  //             icon: TableIcon,
  //             path: "/analytics/reports/financial",
  //           },
  //         ],
  //       },
  //       {
  //         id: "charts",
  //         title: "Charts & Graphs",
  //         icon: PieIcon,
  //         children: [
  //           {
  //             id: "pie-charts",
  //             title: "Pie Charts",
  //             icon: PieIcon,
  //             path: "/analytics/charts/pie",
  //           },
  //           {
  //             id: "line-charts",
  //             title: "Line Charts",
  //             icon: TimelineIcon,
  //             path: "/analytics/charts/line",
  //           },
  //           {
  //             id: "bar-charts",
  //             title: "Bar Charts",
  //             icon: ChartIcon,
  //             path: "/analytics/charts/bar",
  //           },
  //         ],
  //       },
  //       {
  //         id: "real-time",
  //         title: "Real-time Analytics",
  //         icon: TrendingIcon,
  //         path: "/analytics/realtime",
  //       },
  //     ],
  //   },
  //   {
  //     id: "ecommerce",
  //     title: "E-Commerce",
  //     icon: ShoppingCartIcon,
  //     children: [
  //       {
  //         id: "products",
  //         title: "Products",
  //         icon: InventoryIcon,
  //         children: [
  //           {
  //             id: "all-products",
  //             title: "All Products",
  //             icon: StoreIcon,
  //             path: "/ecommerce/products/all",
  //           },
  //           {
  //             id: "categories",
  //             title: "Categories",
  //             icon: CategoryIcon,
  //             path: "/ecommerce/products/categories",
  //           },
  //           {
  //             id: "inventory",
  //             title: "Inventory",
  //             icon: InventoryIcon,
  //             path: "/ecommerce/products/inventory",
  //           },
  //         ],
  //       },
  //       {
  //         id: "orders",
  //         title: "Orders",
  //         icon: OrderIcon,
  //         children: [
  //           {
  //             id: "all-orders",
  //             title: "All Orders",
  //             icon: OrderIcon,
  //             path: "/ecommerce/orders/all",
  //           },
  //           {
  //             id: "pending-orders",
  //             title: "Pending Orders",
  //             icon: NotificationIcon,
  //             path: "/ecommerce/orders/pending",
  //           },
  //           {
  //             id: "shipped-orders",
  //             title: "Shipped Orders",
  //             icon: ShippingIcon,
  //             path: "/ecommerce/orders/shipped",
  //           },
  //         ],
  //       },
  //       {
  //         id: "payments",
  //         title: "Payments",
  //         icon: PaymentIcon,
  //         path: "/ecommerce/payments",
  //       },
  //       {
  //         id: "reviews",
  //         title: "Reviews",
  //         icon: ReviewIcon,
  //         path: "/ecommerce/reviews",
  //       },
  //     ],
  //   },
  //   {
  //     id: "security",
  //     title: "Security",
  //     icon: SecurityIcon,
  //     children: [
  //       {
  //         id: "authentication",
  //         title: "Authentication",
  //         icon: LockIcon,
  //         children: [
  //           {
  //             id: "login-settings",
  //             title: "Login Settings",
  //             icon: LockIcon,
  //             path: "/security/auth/login",
  //           },
  //           {
  //             id: "password-policy",
  //             title: "Password Policy",
  //             icon: KeyIcon,
  //             path: "/security/auth/password",
  //           },
  //           {
  //             id: "two-factor",
  //             title: "Two-Factor Auth",
  //             icon: ShieldIcon,
  //             path: "/security/auth/2fa",
  //           },
  //         ],
  //       },
  //       {
  //         id: "permissions",
  //         title: "Permissions",
  //         icon: ShieldIcon,
  //         path: "/security/permissions",
  //       },
  //       {
  //         id: "audit-logs",
  //         title: "Audit Logs",
  //         icon: ReportsIcon,
  //         path: "/security/audit",
  //       },
  //     ],
  //   },
  //   {
  //     id: "settings",
  //     title: "Settings",
  //     icon: SettingsIcon,
  //     path: "/settings",
  //   },
];
